export const dualPoolStakingAbi = [
  {
    type: "event",
    name: "EmergencyWithdrawn",
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "principal", type: "uint256" },
      { indexed: false, name: "rewardsForfeited", type: "uint256" },
      { indexed: true, name: "pool", type: "uint8" },
      { indexed: false, name: "withdrawnAt", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ForceClaimed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "paidA", type: "uint256" },
      { indexed: false, name: "paidB", type: "uint256" },
      { indexed: false, name: "unpaidA", type: "uint256" },
      { indexed: false, name: "unpaidB", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "OutboundTransfer",
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: true, name: "to", type: "address" },
      { indexed: false, name: "grossAmount", type: "uint256" },
      { indexed: false, name: "netReceived", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "poolA",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "stakingToken", type: "address" },
      { name: "totalStaked", type: "uint256" },
      { name: "rewardRate", type: "uint256" },
      { name: "lastUpdateTime", type: "uint256" },
      { name: "accRewardPerToken", type: "uint256" },
      { name: "availableRewards", type: "uint256" },
      { name: "periodFinish", type: "uint256" },
      { name: "badDebt", type: "uint256" },
      { name: "totalPending", type: "uint256" },
      { name: "dust", type: "uint256" },
      { name: "tvlCap", type: "uint256" },
      { name: "minStakeAmount", type: "uint256" },
      { name: "rewardDuration", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "poolB",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "stakingToken", type: "address" },
      { name: "totalStaked", type: "uint256" },
      { name: "rewardRate", type: "uint256" },
      { name: "lastUpdateTime", type: "uint256" },
      { name: "accRewardPerToken", type: "uint256" },
      { name: "availableRewards", type: "uint256" },
      { name: "periodFinish", type: "uint256" },
      { name: "badDebt", type: "uint256" },
      { name: "totalPending", type: "uint256" },
      { name: "dust", type: "uint256" },
      { name: "tvlCap", type: "uint256" },
      { name: "minStakeAmount", type: "uint256" },
      { name: "rewardDuration", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "userInfoA",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "staked", type: "uint256" },
      { name: "rewards", type: "uint256" },
      { name: "rewardPaid", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "userInfoB",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "staked", type: "uint256" },
      { name: "rewards", type: "uint256" },
      { name: "rewardPaid", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "pendingRewardA",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pendingRewardB",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "stakeTimestampB", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "unlockTimeB", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lastClaimTime", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "rewardToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    type: "function",
    name: "maxTotalSupplyBForRewardRateCap",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "claimCooldown", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lockDuration", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "withdrawFeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "midTermFeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "penaltyfeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "minClaimAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "feeRecipient", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "minEarlyExitAmountB", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "maxTransferFeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "unclaimedFeesB", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "userModule", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "adminModule", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "paused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "emergencyMode", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "shutdown", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "poolACatchUpComplete", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "poolBCatchUpComplete", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "crankCatchUpPool", stateMutability: "nonpayable", inputs: [{ name: "pool", type: "uint8" }], outputs: [] },
  { type: "function", name: "stakeA", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawA", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "claimA", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "forceClaimAll", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "notifyRewardAmountA",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "emergencyWithdrawA", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "stakeB", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawB", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "claimB", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "notifyRewardAmountB",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "compoundB", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "emergencyWithdrawB", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "setFees", stateMutability: "nonpayable", inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }], outputs: [] },
  { type: "function", name: "setLockDuration", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setTVLCapA", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setTVLCapB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinStakeAmountA", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinStakeAmountB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setRewardDurationA", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setRewardDurationB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinClaimAmount", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinEarlyExitAmountB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMaxTransferFeeBP", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "rebalanceBudgets", stateMutability: "nonpayable", inputs: [{ type: "uint8" }, { type: "uint8" }, { type: "uint256" }], outputs: [] },
  { type: "function", name: "claimFees", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "pause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "enableEmergencyMode", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "DEFAULT_ADMIN_ROLE", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "ADMIN_ROLE", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "OPERATOR_ROLE", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  {
    type: "function",
    name: "hasRole",
    stateMutability: "view",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ type: "bool" }],
  },
] as const;
