export const dualPoolStakingAbi = [
  {
    type: "event",
    name: "TimelockScheduled",
    anonymous: false,
    inputs: [
      { indexed: true, name: "opId", type: "bytes32" },
      { indexed: true, name: "paramsHash", type: "bytes32" },
      { indexed: false, name: "executeAfter", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "TimelockConsumed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "opId", type: "bytes32" },
      { indexed: true, name: "paramsHash", type: "bytes32" },
      { indexed: false, name: "executedAt", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "TimelockCancelled",
    anonymous: false,
    inputs: [
      { indexed: true, name: "opId", type: "bytes32" },
      { indexed: true, name: "paramsHash", type: "bytes32" },
      { indexed: false, name: "cancelledAt", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "poolA",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "stakingToken", type: "address" },
      { name: "totalStaked", type: "uint256" },
      { name: "rewardRate", type: "uint256" },
      { name: "lastUpdateTime", type: "uint256" },
      { name: "accRewardPerToken", type: "uint256" },
      { name: "availableRewards", type: "uint256" },
      { name: "periodFinish", type: "uint256" },
      { name: "badDebt", type: "uint256" },
      { name: "totalPending", type: "uint256" },
      { name: "dust", type: "uint256" },
      { name: "tvlCap", type: "uint256" },
      { name: "minStakeAmount", type: "uint256" },
      { name: "rewardDuration", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "poolB",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "stakingToken", type: "address" },
      { name: "totalStaked", type: "uint256" },
      { name: "rewardRate", type: "uint256" },
      { name: "lastUpdateTime", type: "uint256" },
      { name: "accRewardPerToken", type: "uint256" },
      { name: "availableRewards", type: "uint256" },
      { name: "periodFinish", type: "uint256" },
      { name: "badDebt", type: "uint256" },
      { name: "totalPending", type: "uint256" },
      { name: "dust", type: "uint256" },
      { name: "tvlCap", type: "uint256" },
      { name: "minStakeAmount", type: "uint256" },
      { name: "rewardDuration", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "userInfoA",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "staked", type: "uint256" },
      { name: "rewards", type: "uint256" },
      { name: "rewardPaid", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "userInfoB",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "staked", type: "uint256" },
      { name: "rewards", type: "uint256" },
      { name: "rewardPaid", type: "uint256" },
    ],
  },
  { type: "function", name: "stakeTimestampB", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "unlockTimeB", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lastClaimTime", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "rewardToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    type: "function",
    name: "maxTotalSupplyBForRewardRateCap",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "claimCooldown", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lockDuration", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "withdrawFeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "midTermFeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "penaltyfeeBP", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "minClaimAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "unclaimedFeesB", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "paused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "emergencyMode", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "shutdown", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "pendingOps", stateMutability: "view", inputs: [{ name: "opId", type: "bytes32" }], outputs: [{ name: "executeAfter", type: "uint256" }, { name: "paramsHash", type: "bytes32" }] },
  { type: "function", name: "stakeA", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawA", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "claimA", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "notifyRewardAmountA",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "emergencyWithdrawA", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "stakeB", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawB", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "claimB", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "notifyRewardAmountB",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "compoundB", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "emergencyWithdrawB", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "setFees", stateMutability: "nonpayable", inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }], outputs: [] },
  { type: "function", name: "setLockDuration", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setTVLCapA", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setTVLCapB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinStakeAmountA", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinStakeAmountB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setRewardDurationA", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setRewardDurationB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinClaimAmount", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinEarlyExitAmountB", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "setMaxTransferFeeBP", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "rebalanceBudgets", stateMutability: "nonpayable", inputs: [{ type: "uint8" }, { type: "uint8" }, { type: "uint256" }], outputs: [] },
  { type: "function", name: "claimFees", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "pause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "enableEmergencyMode", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "cancelTimelock", stateMutability: "nonpayable", inputs: [{ name: "opId", type: "bytes32" }], outputs: [] },
  { type: "function", name: "ADMIN_ROLE", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "OPERATOR_ROLE", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  {
    type: "function",
    name: "hasRole",
    stateMutability: "view",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ type: "bool" }],
  },
] as const;
