/** DualPoolStakingAdmin 门面：与 `src/DualPoolStakingAdmin.sol` 对齐（供 Timelock `encodeFunctionData`）。 */
export const dualPoolStakingAdminAbi = [
  {
    type: "function",
    name: "timelockGovernance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "timelockSuper",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "setFees",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newWithdrawFeeBP", type: "uint256" },
      { name: "newMidTermFeeBP", type: "uint256" },
      { name: "newPenaltyFeeBP", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "setLockDuration", stateMutability: "nonpayable", inputs: [{ name: "newLockDuration", type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinEarlyExitAmountB", stateMutability: "nonpayable", inputs: [{ name: "newMin", type: "uint256" }], outputs: [] },
  { type: "function", name: "setMaxTransferFeeBP", stateMutability: "nonpayable", inputs: [{ name: "newMaxTransferFeeBP", type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinClaimAmount", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "setRewardDurationA", stateMutability: "nonpayable", inputs: [{ name: "duration", type: "uint256" }], outputs: [] },
  { type: "function", name: "setRewardDurationB", stateMutability: "nonpayable", inputs: [{ name: "duration", type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinStakeAmountA", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "setMinStakeAmountB", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "setTVLCapA", stateMutability: "nonpayable", inputs: [{ name: "cap", type: "uint256" }], outputs: [] },
  { type: "function", name: "setTVLCapB", stateMutability: "nonpayable", inputs: [{ name: "cap", type: "uint256" }], outputs: [] },
  { type: "function", name: "setFeeRecipient", stateMutability: "nonpayable", inputs: [{ name: "newRecipient", type: "address" }], outputs: [] },
  { type: "function", name: "setForfeitedRecipient", stateMutability: "nonpayable", inputs: [{ name: "newRecipient", type: "address" }], outputs: [] },
  {
    type: "function",
    name: "rebalanceBudgets",
    stateMutability: "nonpayable",
    inputs: [
      { name: "from", type: "uint8" },
      { name: "to", type: "uint8" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "claimFees", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "resolveBadDebt", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  {
    type: "function",
    name: "recoverToken",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "activateShutdown", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "forceShutdownFinalize", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "setUserModule", stateMutability: "nonpayable", inputs: [{ name: "newModule", type: "address" }], outputs: [] },
  { type: "function", name: "setAdminModule", stateMutability: "nonpayable", inputs: [{ name: "newModule", type: "address" }], outputs: [] },
  {
    type: "function",
    name: "setAdmin",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newAdmin", type: "address" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setOperator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newOperator", type: "address" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
  },
] as const;
