/** 合约控制台文案（统一中文；链上标识符如 NORMAL、OPERATOR_ROLE 保留英文） */
export const CONSOLE_COPY = {
  brand: {
    title: "DualPool 控制台",
    subtitle: "合约交互 · 运维 · 治理",
  },
  nav: {
    hub: "总览",
    governance: "治理",
    aria: "控制台导航",
  },
  roleBadge: {
    timelock: "Timelock",
    operator: "运维",
  },
  common: {
    pending: "处理中…",
    refresh: "刷新",
    refreshing: "刷新中…",
    notConnected: "未连接钱包",
    walletNotConnected: "钱包未连接",
    noPosition: "暂无仓位",
    loading: "加载中…",
    loadFailed: "加载失败",
    claim: "领取",
    compound: "复利",
    emergencyWithdraw: "紧急退出",
    stake: "质押",
    withdraw: "赎回",
    notify: "注入奖励",
    approveNotify: "授权并注入",
    enableEmergency: "开启紧急模式",
  },
  access: {
    operator: "运维权限",
    readOnly: "只读",
    disconnected: "未连接",
    checking: "检查中…",
    granted: "已授权",
    none: "无",
    actionable: "可操作",
  },
  hub: {
    eyebrow: "运维指挥台",
    title: "合约控制台",
    intro:
      "类 Safe / Aave Admin 的运维面板：先看钱包权限、协议健康和 Timelock 域，再进入具体合约操作。普通用户请使用",
    productLink: "产品界面",
    status: "协议状态",
    badDebt: "坏账",
    badDebtPresent: "存在",
    badDebtClear: "无",
    activeWallet: "当前钱包",
    chainId: "链 ID",
    access: "访问权限",
    protocolStatus: "协议状态",
    protocolStatusSub: "核心执行模式",
    globalBadDebt: "全局坏账",
    globalBadDebtSub: "TokenB 记账负债",
    poolATvl: "灵活池 TVL",
    poolATvlSub: "TokenA 已质押",
    poolBTvl: "锁仓池 TVL",
    poolBTvlSub: "TokenB 已锁仓",
    permissionMatrix: "权限矩阵",
    permissionMatrixSub: "当前钱包可执行的控制域。",
    poolAOps: "灵活池运维",
    poolAOpsDesc:
      "stakeA / withdrawA / claimA / emergencyWithdrawA；含奖励注入、rewardRate 与用户仓位原始字段。",
    poolBOps: "锁仓池运维",
    poolBOpsDesc:
      "stakeB / withdrawB / claimB / compoundB；含 unlockTime、WADP stakeTimestamp 和退出费率调试。",
    governanceQueue: "治理队列",
    governanceQueueDesc: "Timelock 排队 / 执行 / 取消、参数更新、模块升级和受限管理操作。",
    governanceRestricted: "治理受限",
    governanceRestrictedDesc: "需要 OPERATOR_ROLE 或 Timelock 治理角色后可见。",
    contractRegistry: "合约注册表",
    contractRegistrySub: "生产/测试部署地址，点击进入区块浏览器。",
    badgePool: "池子",
    badgeRestricted: "受限",
    operatorRoleDesc: "暂停、奖励注资、紧急模式等热路径能力。",
    proposerDesc: "创建治理排队操作，进入延迟窗口。",
    executorDesc: "在延迟结束后执行已排队操作。",
    cancellerDesc: "取消尚未执行的治理操作。",
  },
  poolA: {
    eyebrow: "灵活池控制台",
    title: "灵活池",
    desc: "TokenA 质押、TokenB 奖励领取、紧急退出与奖励注资调试入口。这里展示原始链上字段，适合运维核对交易前状态。",
    metrics: "灵活池指标",
    stakeTitle: "质押 TokenA",
    stakeHint: "灵活池无锁仓、无退出罚金、无赎回手续费。",
    withdrawTitle: "赎回 TokenA",
    position: "我的仓位",
    staked: "已质押",
    pendingRewards: "待领取奖励",
    stakingDuration: "质押时长",
    rewardPaidLifetime: "累计已发放奖励",
    claimCooldown: "领取冷却",
    claimUnavailable: "暂不可领取",
    emergencyUnavailable: "暂不可紧急退出",
    walletDesc: "连接钱包后读取质押本金、奖励与领取冷却。",
    noPositionDesc: "质押 TokenA 后，这里会显示仓位与可领取奖励。",
    emergencyTitle: "紧急退出（灵活池）",
    principalReturned: "预计返还本金",
    rewardsForfeited: "预计放弃奖励",
    emergencyWarning: "未领取奖励将全部放弃，链上操作不可撤销。",
    emergencyConfirm: "确认紧急退出",
  },
  poolB: {
    eyebrow: "锁仓池控制台",
    title: "锁仓池",
    desc: "TokenB 锁仓、复利、提前退出费用与紧急退出调试入口。交易前先核对 unlockTime、WADP 时间戳和当前协议状态。",
    metrics: "锁仓池指标",
    stakeTitle: "质押 TokenB",
    stakeHint: "含锁仓周期、费率档位、提前退出罚金与可选复利。",
    withdrawTitle: "赎回 TokenB",
    position: "我的仓位",
    staked: "已质押",
    rewards: "待领取奖励",
    unlockTime: "解锁时间 (unlockTime)",
    stakeTimestamp: "质押时间戳 (WADP stakeTimestamp)",
    lastClaimTime: "上次领取 (lastClaimTime)",
    walletDesc: "连接钱包后读取锁仓本金、奖励、解锁时间与领取冷却。",
    noPositionDesc: "质押 TokenB 后，这里会显示解锁进度和可领取奖励。",
    compoundTitle: "确认复利",
    compoundPoolA: "灵活池待领（估）",
    compoundPoolB: "锁仓池待领（估）",
    compoundTotal: "合计复利（估）",
    compoundWarning: "复利为链上操作，实际结果可能与估算略有偏差。",
    compoundConfirm: "确认复利",
    emergencyTitle: "紧急退出（锁仓池）",
    principalReturned: "预计返还本金",
    rewardsForfeited: "预计放弃奖励",
    emergencyWarning: "未领取奖励将全部放弃，链上操作不可撤销。",
    emergencyConfirm: "确认紧急退出",
  },
  governance: {
    eyebrow: "受限治理",
    title: "治理",
    desc: "Timelock 队列、执行、取消与核心运维热路径。该区域只面向具备治理或运维角色的钱包。",
    connectWallet: "请先连接钱包",
    connectWalletDesc: "该页包含 TimelockController 治理角色和 DualPoolStaking 的 OPERATOR_ROLE 热路径。",
    loadingRoles: "正在读取链上角色",
    loadingRolesDesc: "检查 Timelock 与运维权限中。",
    noPermission: "当前钱包无治理权限",
    noPermissionDesc: "需要 TimelockController 的 PROPOSER / EXECUTOR / CANCELLER 之一，或核心 OPERATOR_ROLE。",
  },
  stats: {
    tvl: "总锁仓 TVL",
    apr: "预估 APR（线性）",
    apy: "预估 APY（日复利）",
    yourShare: "我的 TVL 占比",
    footnote:
      "APR 由当前 rewardRate 与 TVL 线性换算（质押与奖励单位/精度一致）。APY 为日复利近似值；APR 过高时不展示。不代表未来收益承诺。",
  },
  operator: {
    title: "运维 · 注入奖励",
    titleCompact: (pool: "A" | "B") => `${pool === "A" ? "灵活池" : "锁仓池"} · 注入奖励`,
    amountLabel: "数量（TokenB）",
    durationLabel: "周期（秒）",
    duration7d: "7 天",
    duration30d: "30 天",
    duration90d: "90 天",
    duration365d: "365 天",
  },
  withdraw: {
    confirmTitle: "确认赎回",
    confirmLocked: "锁仓仓位：提前退出将对本金收取罚金，请确认到账金额。",
    confirmNormal: "网络 Gas 另计。数值基于当前链上参数的估算。",
    confirmSubmit: "提交赎回",
    smartSuggestions: "智能建议",
    comparison: "赎回对比",
    comparisonHint: "相同本金基准；下一行使用更优时间窗口的预估费率/罚金。",
    withdrawNow: "立即赎回（到账）",
    withdrawLater: "延后赎回（到账）",
    difference: "差额（延后 − 立即）",
    basisPct: "占本金",
    setReminder: "设置等待提醒",
    enterAmountHint: "输入数量（或使用最大仓位）以对比到账金额。",
    noLockFee: "本池无锁仓、罚金或赎回手续费。",
    lockedPenalty: "锁仓中：提前退出罚金",
    feeTier: "费率档位：等待后最多可降低",
    noDelayAdvantage: "在当前基准下，延后操作无费率/罚金优势。",
    emergencyHint: "协议处于紧急模式：请使用紧急退出路径。",
    amountPlaceholder: "赎回数量",
    max: "最大",
    submit: "赎回",
    exceedsBalance: "超过质押余额",
    inputLabel: "输入",
    tagNow: "立即赎回",
    tagWait: "建议等待",
    tagEmergency: "使用紧急退出",
    principal: "本金",
    receiveEst: "预计到账",
    feeEst: "手续费（估）",
    penaltyEst: "罚金（估）",
    optimalNow: "当前最优",
  },
  forceClaim: {
    title: "跨池领取（forceClaimAll）",
    desc: "一次性结算灵活池与锁仓池的 TokenB 奖励。仅在关停或存在坏账时开放；按链上残值部分兑付，顺序为先 A 后 B。",
    totalPending: "合计待领",
    cooldown: "领取冷却",
    submit: "强制跨池领取",
  },
  hubRoles: {
    operator: "OPERATOR_ROLE",
    proposer: "Timelock PROPOSER",
    executor: "Timelock EXECUTOR",
    canceller: "Timelock CANCELLER",
  },
} as const;
