"use client";

import { useMemo } from "react";

import { useI18n } from "@/lib/i18n";

/**
 * 合约控制台文案 hook（`/console/*`）。
 * 键路径与 `console.*` 语言包对齐；链上标识符（NORMAL、OPERATOR_ROLE 等）保持英文不翻译。
 *
 * 产品页请用 `useI18n()`，勿引用本 hook。
 */
export function useConsoleCopy() {
  const { t } = useI18n();

  return useMemo(
    () => ({
      brand: {
        title: t("console.brand.title"),
        subtitle: t("console.brand.subtitle"),
      },
      nav: {
        hub: t("console.nav.hub"),
        governance: t("console.nav.governance"),
        poolFlexible: t("console.nav.poolFlexible"),
        poolLocked: t("console.nav.poolLocked"),
        aria: t("console.nav.aria"),
      },
      roleBadge: {
        timelock: t("console.roleBadge.timelock"),
        operator: t("console.roleBadge.operator"),
      },
      common: {
        pending: t("console.common.pending"),
        refresh: t("console.common.refresh"),
        refreshing: t("console.common.refreshing"),
        notConnected: t("console.common.notConnected"),
        walletNotConnected: t("console.common.walletNotConnected"),
        noPosition: t("console.common.noPosition"),
        loading: t("console.common.loading"),
        loadFailed: t("console.common.loadFailed"),
        claim: t("console.common.claim"),
        compound: t("console.common.compound"),
        emergencyWithdraw: t("console.common.emergencyWithdraw"),
        stake: t("console.common.stake"),
        withdraw: t("console.common.withdraw"),
        notify: t("console.common.notify"),
        approveNotify: t("console.common.approveNotify"),
        enableEmergency: t("console.common.enableEmergency"),
      },
      access: {
        operator: t("console.access.operator"),
        readOnly: t("console.access.readOnly"),
        disconnected: t("console.access.disconnected"),
        checking: t("console.access.checking"),
        granted: t("console.access.granted"),
        none: t("console.access.none"),
        actionable: t("console.access.actionable"),
      },
      hub: {
        eyebrow: t("console.hub.eyebrow"),
        title: t("console.hub.title"),
        intro: t("console.hub.intro"),
        productLink: t("console.hub.productLink"),
        status: t("console.hub.status"),
        badDebt: t("console.hub.badDebt"),
        badDebtPresent: t("console.hub.badDebtPresent"),
        badDebtClear: t("console.hub.badDebtClear"),
        activeWallet: t("console.hub.activeWallet"),
        chainId: t("console.hub.chainId"),
        access: t("console.hub.access"),
        protocolStatus: t("console.hub.protocolStatus"),
        protocolStatusSub: t("console.hub.protocolStatusSub"),
        globalBadDebt: t("console.hub.globalBadDebt"),
        globalBadDebtSub: t("console.hub.globalBadDebtSub"),
        poolATvl: t("console.hub.poolATvl"),
        poolATvlSub: t("console.hub.poolATvlSub"),
        poolBTvl: t("console.hub.poolBTvl"),
        poolBTvlSub: t("console.hub.poolBTvlSub"),
        permissionMatrix: t("console.hub.permissionMatrix"),
        permissionMatrixSub: t("console.hub.permissionMatrixSub"),
        poolAOps: t("console.hub.poolAOps"),
        poolAOpsDesc: t("console.hub.poolAOpsDesc"),
        poolBOps: t("console.hub.poolBOps"),
        poolBOpsDesc: t("console.hub.poolBOpsDesc"),
        governanceQueue: t("console.hub.governanceQueue"),
        governanceQueueDesc: t("console.hub.governanceQueueDesc"),
        governanceRestricted: t("console.hub.governanceRestricted"),
        governanceRestrictedDesc: t("console.hub.governanceRestrictedDesc"),
        contractRegistry: t("console.hub.contractRegistry"),
        contractRegistrySub: t("console.hub.contractRegistrySub"),
        badgePool: t("console.hub.badgePool"),
        badgeRestricted: t("console.hub.badgeRestricted"),
        operatorRoleDesc: t("console.hub.operatorRoleDesc"),
        proposerDesc: t("console.hub.proposerDesc"),
        executorDesc: t("console.hub.executorDesc"),
        cancellerDesc: t("console.hub.cancellerDesc"),
        roleBasedOps: {
          title: t("console.hub.roleBasedOps.title"),
          subtitle: t("console.hub.roleBasedOps.subtitle"),
          privileged: t("console.hub.roleBasedOps.privileged"),
          connected: t("console.hub.roleBasedOps.connected"),
          connectWallet: t("console.hub.roleBasedOps.connectWallet"),
          availableSection: t("console.hub.roleBasedOps.availableSection"),
          lockedSection: t("console.hub.roleBasedOps.lockedSection"),
        },
        operationDomains: {
          readonly: {
            title: t("console.hub.operationDomains.readonly.title"),
            desc: t("console.hub.operationDomains.readonly.desc"),
            badge: t("console.hub.operationDomains.readonly.badge"),
          },
          poolAUser: {
            title: t("console.hub.operationDomains.poolAUser.title"),
            desc: t("console.hub.operationDomains.poolAUser.desc"),
            badgeAvailable: t("console.hub.operationDomains.poolAUser.badgeAvailable"),
            badgeNeedConnect: t("console.hub.operationDomains.poolAUser.badgeNeedConnect"),
          },
          poolBUser: {
            title: t("console.hub.operationDomains.poolBUser.title"),
            desc: t("console.hub.operationDomains.poolBUser.desc"),
            badgeAvailable: t("console.hub.operationDomains.poolBUser.badgeAvailable"),
            badgeNeedConnect: t("console.hub.operationDomains.poolBUser.badgeNeedConnect"),
          },
          operator: {
            title: t("console.hub.operationDomains.operator.title"),
            desc: t("console.hub.operationDomains.operator.desc"),
            badgeGranted: t("console.hub.operationDomains.operator.badgeGranted"),
            badgeRequired: t("console.hub.operationDomains.operator.badgeRequired"),
          },
          adminRole: {
            title: t("console.hub.operationDomains.adminRole.title"),
            desc: t("console.hub.operationDomains.adminRole.desc"),
            badgeGranted: t("console.hub.operationDomains.adminRole.badgeGranted"),
            badgeRequired: t("console.hub.operationDomains.adminRole.badgeRequired"),
          },
          timelock48h: {
            title: t("console.hub.operationDomains.timelock48h.title"),
            desc: t("console.hub.operationDomains.timelock48h.desc"),
            badgeGranted: t("console.hub.operationDomains.timelock48h.badgeGranted"),
            badgeRequired: t("console.hub.operationDomains.timelock48h.badgeRequired"),
          },
          timelock72h: {
            title: t("console.hub.operationDomains.timelock72h.title"),
            desc: t("console.hub.operationDomains.timelock72h.desc"),
            badgeGranted: t("console.hub.operationDomains.timelock72h.badgeGranted"),
            badgeRequired: t("console.hub.operationDomains.timelock72h.badgeRequired"),
          },
        },
        contractNames: {
          dualPoolStaking: t("console.hub.contractNames.dualPoolStaking"),
          dualPoolStakingAdmin: t("console.hub.contractNames.dualPoolStakingAdmin"),
          dualPoolAdminModule: t("console.hub.contractNames.dualPoolAdminModule"),
          timelock48h: t("console.hub.contractNames.timelock48h"),
          timelockSuper72h: t("console.hub.contractNames.timelockSuper72h"),
        },
      },
      walletRole: {
        operatorRole: t("console.walletRole.operatorRole"),
        adminRole: t("console.walletRole.adminRole"),
        proposer48h: t("console.walletRole.proposer48h"),
        executor48h: t("console.walletRole.executor48h"),
        canceller48h: t("console.walletRole.canceller48h"),
        proposer72h: t("console.walletRole.proposer72h"),
        executor72h: t("console.walletRole.executor72h"),
        canceller72h: t("console.walletRole.canceller72h"),
        noneReadOnly: t("console.walletRole.noneReadOnly"),
        addressNotConnected: t("console.walletRole.addressNotConnected"),
        addressChecking: t("console.walletRole.addressChecking"),
        addressWithRoles: t("console.walletRole.addressWithRoles"),
      },
      poolA: {
        eyebrow: t("console.poolA.eyebrow"),
        title: t("console.poolA.title"),
        desc: t("console.poolA.desc"),
        metrics: t("console.poolA.metrics"),
        stakeTitle: t("console.poolA.stakeTitle"),
        stakeHint: t("console.poolA.stakeHint"),
        withdrawTitle: t("console.poolA.withdrawTitle"),
        position: t("console.poolA.position"),
        staked: t("console.poolA.staked"),
        pendingRewards: t("console.poolA.pendingRewards"),
        stakingDuration: t("console.poolA.stakingDuration"),
        rewardPaidLifetime: t("console.poolA.rewardPaidLifetime"),
        claimCooldown: t("console.poolA.claimCooldown"),
        claimUnavailable: t("console.poolA.claimUnavailable"),
        emergencyUnavailable: t("console.poolA.emergencyUnavailable"),
        walletDesc: t("console.poolA.walletDesc"),
        noPositionDesc: t("console.poolA.noPositionDesc"),
        emergencyTitle: t("console.poolA.emergencyTitle"),
        principalReturned: t("console.poolA.principalReturned"),
        rewardsForfeited: t("console.poolA.rewardsForfeited"),
        emergencyWarning: t("console.poolA.emergencyWarning"),
        emergencyConfirm: t("console.poolA.emergencyConfirm"),
        stakeDurationFull: t("console.poolA.stakeDurationFull"),
        stakeDurationHours: t("console.poolA.stakeDurationHours"),
        stakeDurationMins: t("console.poolA.stakeDurationMins"),
        actionWithdraw: t("console.poolA.actionWithdraw"),
        actionClaim: t("console.poolA.actionClaim"),
      },
      poolB: {
        eyebrow: t("console.poolB.eyebrow"),
        title: t("console.poolB.title"),
        desc: t("console.poolB.desc"),
        metrics: t("console.poolB.metrics"),
        stakeTitle: t("console.poolB.stakeTitle"),
        stakeHint: t("console.poolB.stakeHint"),
        withdrawTitle: t("console.poolB.withdrawTitle"),
        position: t("console.poolB.position"),
        staked: t("console.poolB.staked"),
        rewards: t("console.poolB.rewards"),
        unlockTime: t("console.poolB.unlockTime"),
        stakeTimestamp: t("console.poolB.stakeTimestamp"),
        lastClaimTime: t("console.poolB.lastClaimTime"),
        walletDesc: t("console.poolB.walletDesc"),
        noPositionDesc: t("console.poolB.noPositionDesc"),
        compoundTitle: t("console.poolB.compoundTitle"),
        compoundPoolA: t("console.poolB.compoundPoolA"),
        compoundPoolB: t("console.poolB.compoundPoolB"),
        compoundTotal: t("console.poolB.compoundTotal"),
        compoundWarning: t("console.poolB.compoundWarning"),
        compoundConfirm: t("console.poolB.compoundConfirm"),
        emergencyTitle: t("console.poolB.emergencyTitle"),
        principalReturned: t("console.poolB.principalReturned"),
        rewardsForfeited: t("console.poolB.rewardsForfeited"),
        emergencyWarning: t("console.poolB.emergencyWarning"),
        emergencyConfirm: t("console.poolB.emergencyConfirm"),
        actionWithdraw: t("console.poolB.actionWithdraw"),
        actionClaim: t("console.poolB.actionClaim"),
      },
      governance: {
        eyebrow: t("console.governance.eyebrow"),
        title: t("console.governance.title"),
        desc: t("console.governance.desc"),
        connectWallet: t("console.governance.connectWallet"),
        connectWalletDesc: t("console.governance.connectWalletDesc"),
        loadingRoles: t("console.governance.loadingRoles"),
        loadingRolesDesc: t("console.governance.loadingRolesDesc"),
        noPermission: t("console.governance.noPermission"),
        noPermissionDesc: t("console.governance.noPermissionDesc"),
      },
      stats: {
        tvl: t("console.stats.tvl"),
        apr: t("console.stats.apr"),
        apy: t("console.stats.apy"),
        apyTooHigh: t("console.stats.apyTooHigh"),
        yourShare: t("console.stats.yourShare"),
        footnote: t("console.stats.footnote"),
      },
      operator: {
        title: t("console.operator.title"),
        titleCompact: (pool: "A" | "B") =>
          t(pool === "A" ? "console.operator.titleCompactFlexible" : "console.operator.titleCompactLocked"),
        amountLabel: t("console.operator.amountLabel"),
        durationLabel: t("console.operator.durationLabel"),
        duration7d: t("console.operator.duration7d"),
        duration30d: t("console.operator.duration30d"),
        duration90d: t("console.operator.duration90d"),
        duration365d: t("console.operator.duration365d"),
        roleHint: t("console.operator.roleHint"),
        roleHintPrefix: t("console.operator.roleHintPrefix"),
        roleHintMiddle: t("console.operator.roleHintMiddle"),
        roleHintSuffix: t("console.operator.roleHintSuffix"),
        errAmountRequired: t("console.operator.errAmountRequired"),
        errAmountInvalid: t("console.operator.errAmountInvalid"),
        errAmountPositive: t("console.operator.errAmountPositive"),
        errDurationInteger: t("console.operator.errDurationInteger"),
        errDurationRange: (min: string, max: string) => t("console.operator.errDurationRange", { min, max }),
        approvalNeeded: t("console.operator.approvalNeeded"),
        approvalSufficient: t("console.operator.approvalSufficient"),
      },
      withdraw: {
        confirmTitle: t("console.withdraw.confirmTitle"),
        confirmLocked: t("console.withdraw.confirmLocked"),
        confirmNormal: t("console.withdraw.confirmNormal"),
        confirmSubmit: t("console.withdraw.confirmSubmit"),
        smartSuggestions: t("console.withdraw.smartSuggestions"),
        comparison: t("console.withdraw.comparison"),
        comparisonHint: t("console.withdraw.comparisonHint"),
        withdrawNow: t("console.withdraw.withdrawNow"),
        withdrawLater: t("console.withdraw.withdrawLater"),
        difference: t("console.withdraw.difference"),
        basisPct: t("console.withdraw.basisPct"),
        setReminder: t("console.withdraw.setReminder"),
        enterAmountHint: t("console.withdraw.enterAmountHint"),
        noLockFee: t("console.withdraw.noLockFee"),
        lockedPenalty: t("console.withdraw.lockedPenalty"),
        feeTier: t("console.withdraw.feeTier"),
        noDelayAdvantage: t("console.withdraw.noDelayAdvantage"),
        emergencyHint: t("console.withdraw.emergencyHint"),
        amountPlaceholder: t("console.withdraw.amountPlaceholder"),
        max: t("console.withdraw.max"),
        submit: t("console.withdraw.submit"),
        exceedsBalance: t("console.withdraw.exceedsBalance"),
        inputLabel: t("console.withdraw.inputLabel"),
        tagNow: t("console.withdraw.tagNow"),
        tagWait: t("console.withdraw.tagWait"),
        tagEmergency: t("console.withdraw.tagEmergency"),
        principal: t("console.withdraw.principal"),
        receiveEst: t("console.withdraw.receiveEst"),
        feeEst: t("console.withdraw.feeEst"),
        penaltyEst: t("console.withdraw.penaltyEst"),
        optimalNow: t("console.withdraw.optimalNow"),
        exceedsMaxTitle: t("console.withdraw.exceedsMaxTitle"),
        exceedsMaxDesc: (amount: string, symbol: string) => t("console.withdraw.exceedsMaxDesc", { amount, symbol }),
        reminderRecorded: t("console.withdraw.reminderRecorded"),
        reminderUnlockDesc: (days: number, penaltyPct: string, unlockDate: string) =>
          t("console.withdraw.reminderUnlockDesc", { days, penaltyPct, unlockDate }),
        reminderFeeDesc: (days: number) => t("console.withdraw.reminderFeeDesc", { days }),
        reminderUnlockRecorded: (days: number, unlockDate: string) =>
          t("console.withdraw.reminderUnlockRecorded", { days, unlockDate }),
        reminderFeeRecorded: (days: number) => t("console.withdraw.reminderFeeRecorded", { days }),
        maxFilledTitle: t("console.withdraw.maxFilledTitle"),
        maxFilledDesc: t("console.withdraw.maxFilledDesc"),
        feeTierTitle: t("console.withdraw.feeTierTitle"),
        feeTierLt90: (pct: string) => t("console.withdraw.feeTierLt90", { pct }),
        feeTier90_180: (pct: string) => t("console.withdraw.feeTier90_180", { pct }),
        feeTierGt180: t("console.withdraw.feeTierGt180"),
        betterWindow: t("console.withdraw.betterWindow"),
        recordReminder: (days: number) => t("console.withdraw.recordReminder", { days }),
        stakedLine: (amount: string, symbol: string) => t("console.withdraw.stakedLine", { amount, symbol }),
        earnLine: (days: number, amount: string) => t("console.withdraw.earnLine", { days, amount }),
      },
      forceClaim: {
        title: t("console.forceClaim.title"),
        desc: t("console.forceClaim.desc"),
        totalPending: t("console.forceClaim.totalPending"),
        cooldown: t("console.forceClaim.cooldown"),
        submit: t("console.forceClaim.submit"),
        disabledNotAvailable: t("console.forceClaim.disabledNotAvailable"),
        disabledPaused: t("console.forceClaim.disabledPaused"),
        disabledEmergency: t("console.forceClaim.disabledEmergency"),
        disabledCooldown: t("console.forceClaim.disabledCooldown"),
        disabledNoRewards: t("console.forceClaim.disabledNoRewards"),
        disabledZeroLiquidity: t("console.forceClaim.disabledZeroLiquidity"),
        disabledLiquidityUnknown: t("console.forceClaim.disabledLiquidityUnknown"),
        liquidityPartialWarn: (pay: string, pending: string) =>
          t("console.forceClaim.liquidityPartialWarn", { pay, pending }),
        liquidityZeroWarn: t("console.forceClaim.liquidityZeroWarn"),
        confirmPartialTitle: t("console.forceClaim.confirmPartialTitle"),
        confirmPartialWarning: t("console.forceClaim.confirmPartialWarning"),
        estPayout: t("console.forceClaim.estPayout"),
        spendableRemain: t("console.forceClaim.spendableRemain"),
      },
      hubRoles: {
        operator: t("console.hubRoles.operator"),
        proposer: t("console.hubRoles.proposer"),
        executor: t("console.hubRoles.executor"),
        canceller: t("console.hubRoles.canceller"),
      },
    }),
    [t],
  );
}

export type ConsoleCopy = ReturnType<typeof useConsoleCopy>;
